Note:
COPY command to copy source code to Docker image is not necessary because:
python:2.7-onbuild will take care of it.


Confirmation:

$ docker build . -t guillierf/py-red
Sending build context to Docker daemon  9.216kB
Step 1/3 : FROM python:2.7-onbuild
# Executing 3 build triggers...
Step 1/1 : COPY requirements.txt /usr/src/app/
 ---> Using cache
Step 1/1 : RUN pip install --no-cache-dir -r requirements.txt
 ---> Using cache
Step 1/1 : COPY . /usr/src/app
 ---> 684f7b051ea5
Step 2/3 : EXPOSE 5000
 ---> Running in 771e9f7d8287
 ---> ad76e87a68a4
Removing intermediate container 771e9f7d8287
Step 3/3 : CMD python app.py
 ---> Running in e2346542f127
 ---> 7b3add9aed13
Removing intermediate container e2346542f127
Successfully built 7b3add9aed13
Successfully tagged guillierf/py-red:latest

